services: 
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass12345*
    ports:
      - "5987:5432" 
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    #shoud be on default shared network automaticly, no need to define custom network 

  web:
    build: .
    environment:
      FLASK_DEBUG: "true"   
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0        
    ports:
      - "8000:5000"      
    volumes:
      - .:/code      
    depends_on:
      - db       
    #shoud be on default shared network automaticly, no need to define custom network   